name: Release

on:
  push:
    tags:
      - "*.*.*-*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: heroku/heroku:20-build

      env:
        RELEASE_VERSION: ${{ github.ref_name }}
        RELEASE_URL: https://download.imagemagick.org/archive/releases/ImageMagick-${{ github.ref_name }}.tar.xz
        RELEASE_CHECKSUM: 7e5c8db53dd90a0cfc5cc7ca6d34728ed86054b4bc86e9787902285fec1107a8
        RELEASE_CHECKSUM_ALG: sha256

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends \
            libwebp-dev

      - name: Build package
        run: bin/build
        shell: bash

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
